### ISSUE TITLE
Can't deploy on Heroku 

### ISSUE THREAD

**Issue by stepersy** [Aritzherrero4/AffiliateTelegramBot#8]
Hi, I tried to deploy your apps through Heroku, but it says 
"No app.json located in the repo URL provided.
Make sure that an app.json file exists in the project root directory."

Can you repair it? It would be very useful. Thanks!

![Screenshot_20230512-090713_Brave.png](https://github.com/Aritzherrero4/AffiliateTelegramBot/assets/94073410/b0bcbf5b-4f4c-4b37-8eee-1abe9cf8069b)

**Comment by Aritzherrero4** [comment]
Hi!

This error might be due to a change on how Heroku works. Sadly, since they removed the free tier, I no longer use it. 

You can check [Heroku's documentation page](https://devcenter.heroku.com/categories/reference) and check how to add that missing file and it's contents. 

Just FYI, there is another branch on the repo ([local](https://github.com/Aritzherrero4/AffiliateTelegramBot/tree/local)) that contains the code to run it locally. Maybe you can check it out and see if it is easier to adapt, so it works with Heroku.

I'm sorry I cannot help you further. I'll keep this issue open for some time. Maybe other people can add more info.

**Comment by stepersy** [comment]
Thanks for your prompt response. Unfortunately I'm not a developer, so it's quite difficult to me to understand how to create an appropriate app.json file for Heroku, but I'll try. Instead, is possibile to run the program into a VPS such as Oracle Free Tier? If yes, how?
Thanks!

**Comment by Aritzherrero4** [comment]
Yes, If you use the "local" branch on this repo you should be able to deploy it on any server. I run mine on a raspberry pi and it works great.

How it works it's a bit different. The local branch will check if there is anything new on telegram and if there is, it will be processed. 

If there is any rate limiting on the VPS, you might want to configure the check interval and make it bigger. 

You can configure it by changing the value here changing the poll interval:
https://github.com/Aritzherrero4/AffiliateTelegramBot/blob/d71cd7516885465661b361adf86963b3212efda1/bot.py#L82
